# Generated by Django 4.0.4 on 2022-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('studentID', models.PositiveIntegerField()),
                ('level', models.SmallIntegerField()),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dateOfBirth', models.DateField(default='NULL')),
                ('department', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.PositiveBigIntegerField()),
                ('status', models.BooleanField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='NULL', max_length=10)),
            ],
        ),
    ]
