# Generated by Django 4.0.4 on 2022-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dateOfBirth',
            field=models.DateField(default='NULL', verbose_name='Data of birth'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='students',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobileNumber',
            field=models.CharField(max_length=13, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentID',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
    ]
